services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${PW_DB_NAME}
      MYSQL_USER: ${PW_DB_USER}
      MYSQL_PASSWORD: ${PW_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PW_DB_PASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
